version: "3.7"
services: 
    db:
        container_name: postgres_database
        image: postgres:14.1
        volumes:
            - ./data/db:/var/lib/postgresql/data/
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        restart: always
    app:
        container_name: ERV_app
        build: .
        command: >
            bash -c "python ERV/manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/app
        ports: 
            - "8000:8000"
        environment:
            - POSTGRES_NAME=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - DJANGO_KEY=${DJANGO_KEY}
        depends_on: 
            - db
        restart: on-failure