# Generated by Django 4.1.6 on 2023-02-13 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterReadValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.DateField(default=datetime.date.today)),
                ('current_time', models.TimeField()),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExitReadValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.DateField(default=datetime.date.today)),
                ('current_time', models.TimeField()),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(choices=[('nastavnici', 'nastavnici'), ('administracija', 'administracija')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
        migrations.CreateModel(
            name='ERV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_time', models.TimeField()),
                ('flag', models.CharField(max_length=2)),
                ('enter_read_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.enterreadvalue')),
                ('exit_read_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.exitreadvalue')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
    ]
