# Generated by Django 4.1.6 on 2023-02-17 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('administracija', 'administracija'), ('nastavnici', 'nastavnici')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
        migrations.CreateModel(
            name='ERV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.date.today)),
                ('enter_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('flag', models.CharField(choices=[('slobodan dan', 'SL'), ('godisnji odmor', 'GO'), ('rednovni rad', 'RR'), ('rad od kuce', 'RK'), ('putni nalog', 'PN'), ('bolovanje', 'BO')], max_length=14)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.worker')),
            ],
            options={
                'unique_together': {('worker', 'current_date')},
            },
        ),
    ]
