# Generated by Django 4.1.6 on 2023-02-16 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterreadvalue',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterreadvalue',
            name='current_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='enterreadvalue',
            name='current_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erv',
            name='enter_read_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enterreadvalue'),
        ),
        migrations.AlterField(
            model_name='erv',
            name='exit_read_value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exitreadvalue'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(choices=[('administracija', 'administracija'), ('nastavnici', 'nastavnici')], max_length=15),
        ),
    ]
