# Generated by Django 4.1.6 on 2023-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_enterreadvalue_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(choices=[('nastavnici', 'nastavnici'), ('administracija', 'administracija')], max_length=15),
        ),
    ]
