# Generated by Django 4.0.4 on 2022-06-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AAIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=200)),
                ('primary_affiliation', models.CharField(choices=[('', 'None'), ('cjeloživotno obrazovanje', 'Lifelong Learning'), ('djelatnik', 'Employee'), ('gost', 'Guest'), ('korisnik usluge', 'User'), ('student', 'Student'), ('učenik', 'Pupil'), ('vanjski suradnik', 'External Associate')], default='', max_length=24)),
                ('affiliation_expiration_date', models.CharField(default='NONE', max_length=8)),
                ('staff_category', models.CharField(choices=[('', 'None'), ('administrativno osoblje', 'Administrative Staff'), ('ICT podrška', 'Ict Support'), ('istraživači', 'Researchers'), ('nastavno osoblje', 'Teaching Staff'), ('osoblje knjižnice', 'Library Staff'), ('tehničko osoblje', 'Technical Staff')], default='', max_length=23)),
                ('student_category', models.CharField(choices=[('', 'None'), ('osnovnoškolac', 'Primary'), ('srednjoškolac', 'Secondary'), ('izvanredni student:pred-bolonjski studij', 'Part Time Pre Bologna Undergraduate'), ('izvanredni student:preddiplomski sveučilišni studij', 'Part Time Undergraduate'), ('izvanredni student:preddiplomski stručni studij', 'Part Time Professional Undergraduate'), ('izvanredni student:diplomski sveučilišni studij', 'Part Time Graduate'), ('izvanredni student:specijalistički diplomski stručni studij', 'Part Time Specialist Professional Graduate'), ('izvanredni student:integrirani studij', 'Part Time Integrated'), ('izvanredni student:specijalistički poslijediplomski studij', 'Part Time Specialist Post Graduate'), ('izvanredni student:doktorski studij', 'Part Time Phd'), ('redoviti student:pred-bolonjski studij', 'Full Time Pre Bologna Undergraduate'), ('redoviti student:preddiplomski sveučilišni studij', 'Full Time Undergraduate'), ('redoviti student:preddiplomski stručni studij', 'Full Time Professional Undergraduate'), ('redoviti student:diplomski sveučilišni studij', 'Full Time Graduate'), ('redoviti student:specijalistički diplomski stručni studij', 'Full Time Specialist Professional Graduate'), ('redoviti student:integrirani studij', 'Full Time Integrated'), ('redoviti student:specijalistički poslijediplomski studij', 'Full Time Specialist Post Graduate'), ('redoviti student:doktorski studij', 'Full Time Phd'), ('mirovanje statusa studenta', 'Dormant')], default='', max_length=59)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aai_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
